### ISSUE TITLE
关于/jobs 与 /topic/node$ID 的对应关系

### ISSUE THREAD

**Issue by halfss** [huacnlee/homeland#18]
您好：

在使用homeland的过程中，我们遇到了一点小问题

在homeland中， /jobs（招聘这个地址） 实际上是与一个特定的节点可以对应起来的， 是吗？

比如: https://ruby-china.org/jobs 与  https://ruby-china.org/topics/node25 是对应起来的

我们想问一下，这个对应关系在平台中那个地方进行设置的呢？

谢谢

**Comment by huacnlee** [comment]
你提交错地方了 ruby-china/homeland
